### ISSUE TITLE
Issue connecting to the keys.

### ISSUE THREAD

**Issue by chewielewis** [kelvinau/crypto-arbitrage#1]
Hi, just discovered this arbit bot. Looks like you've just started working on it. Im not too handy with python but ive managed to get it all installed but its giving me this 
`IOError: [Errno 2] No such file or directory: '../.keys/bittrexkey'`

The file is there and has not been tampered with

Also when modifying the exchange value in in the triangle arbit page. It tells me. 
`NameError: global name 'bitfinex' is not defined`

**Comment by kelvinau** [comment]
I am changing and refactoring it to make it easier to use. For a quick test run, you can go to the directory of `autocrypto` and run 'python engine_triangularArbitrage.py`, with `exchange` value changed at the bottom. Make sure you submit `true` for `mock` if you want to test is

**Comment by kelvinau** [comment]
Now you can simply use`python main.py -m triangular` to run this. The file structure is renamed a bit to use `bittrex.key` instead. See efbc9cdd65213d9c9ab40177a2bfdf5b0895c72e and 768923786bce0f2f1496319baca9ec1967ca72c4.
