### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ristono** [kelvinau/crypto-arbitrage#10]
C:\Users\Ariez\Desktop\crypto-arbitrage-master>python main.py -m triangular
  File "main.py", line 25
    print 'Mode {0} is not recognized'.format(args.mode)
                                     ^
SyntaxError: invalid syntax

What is wrong?

**Comment by AKimmel** [comment]
This error wants parentheses around the print statement.
print ('Mode {0} is not recognized'.format(args.mode))

**Comment by ristono** [comment]
thanks, how about this

 File "C:\Users\Ariez\Desktop\crypto-arbitrage-master\engines\triangular_arbitrage.py", line 19
    print strftime('%Y%m%d%H%M%S') + ' starting Triangular Arbitrage Engine...'
                 ^
SyntaxError: invalid syntax

**Comment by kelvinau** [comment]
Sorry this is written in Python 2 syntax. Quite a few people used Python 3 and asked me about the same issue. I am updating the readme to explicitly mention this.
