### ISSUE TITLE
There is always a problem

### ISSUE THREAD

**Issue by man5065** [kelvinau/crypto-arbitrage#17]
kelvinau 
      hello.
     I don't know how to program, but I am learning. At the same time, I am also a cryptocurrency trader. So I think your project is very appealing to me. I feel great.
      But unfortunately, I downloaded the program as requested, and after running, there is always a problem. I mainly want to know two questions:
   1. Does this script have to run in cmd.exe?
    2. When I run python main.py -m triangular in cmd.exe, I get an error. The error message is as follows:
     
D:\arbitrage>python main.py -m triangular
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    From engines.triangular_arbitrage import CryptoEngineTriArbitrage
  File "D:\arbitrage\engines\triangular_arbitrage.py", line 3, in <module>
    Import grequests
ImportError: No module named grequests

D:\arbitrage>

   

kelvinau , I hope to get your help.My email: xiaoyan8533@gmail.com.
I also created a Telegram group https://t.me/joinchat/GBLOnRIoWXo7UHVF5R6AUw. 
I hope to meet with you in the group, thank you. Other friends who use this great program are also welcome to join.
Thanks again. Your job is great.

**Comment by man5065** [comment]
by the way ,I have complete" pip install  grequest"

**Comment by man5065** [comment]
HI,the program is running. haha .

**Comment by kelvinau** [comment]
good to hear :)
