### ISSUE TITLE
Kraken get_ticker_lastPrice

### ISSUE THREAD

**Issue by naksi** [kelvinau/crypto-arbitrage#4]
Getting error while running Triangular method on Kraken
**'ExchangeEngine' object has no attribute 'get_ticker_lastPrice'**

**Comment by kelvinau** [comment]
I haven't implemented get_ticker_lastPrice on the other exchanges besides Bittrex. They will be added in the next coming commit.

**Comment by kelvinau** [comment]
Implemented `get_ticker_lastPrice` for Kraken. See 974d2e1c9fde3bf8014007fa10bafd8fa128ec00
